version: '3.9'
name: "go-auth"

services:
  go-auth:
    container_name: go-auth-api
    env_file:
      - .env
    environment:
      POSTGRES_DSN: "user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} host=${POSTGRES_HOST} port=${POSTGRES_PORT} dbname=${POSTGRES_DB}"
    build: ../
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - postgresdb
    networks:
      - goauthnewtwork

  postgresdb:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    networks:
      - goauthnewtwork
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  goauthnewtwork:
    driver: bridge